### PR TITLE
Don't merge, test pr build when en-us enable v3 but loc hasn't 

### PR DESCRIPTION
**Pull request by ByronWU-Docs**
Don't merge, test pr build when en-us enable v3 but loc hasn't

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[b7ecb44](https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz/commits/b7ecb4498e89815e23f6adfc1c2955a2e60761f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2d21f141)

<a id="2d21f141"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz, working directory: C:\LocalRun\W\w5st-s, target branch: master, target branch commit: d4f35698aafe609fdf3bba8a90885cd0aca8fe2c, source commit: b7ecb4498e89815e23f6adfc1c2955a2e60761f5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5Cdba40f77-c0ca-7f55-919e-4973f36f2746%5CPullRequest%5C201911280639090101-5%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ea2L%2F5YtM9US3s1kyra%2F44NXIWrwPnvuI%2FNJwy%2B0rK0%3D&st=2019-11-28T06%3A34%3A20Z&se=2019-12-29T06%3A39%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[b7ecb44](https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz/commits/b7ecb4498e89815e23f6adfc1c2955a2e60761f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d3dee717)

<a id="d3dee717"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz, working directory: C:\LocalRun\W\k33s-s, target branch: master, target branch commit: d4f35698aafe609fdf3bba8a90885cd0aca8fe2c, source commit: b7ecb4498e89815e23f6adfc1c2955a2e60761f5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5Cdba40f77-c0ca-7f55-919e-4973f36f2746%5CPullRequest%5C201911280643498325-5%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l3ubTM6V7FlP7GB0XOuaWG99uPvo41JzYU6gJL3dSQM%3D&st=2019-11-28T06%3A39%3A00Z&se=2019-12-29T06%3A44%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[b7ecb44](https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz/commits/b7ecb4498e89815e23f6adfc1c2955a2e60761f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6cc7f6a4)

<a id="6cc7f6a4"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz, working directory: C:\LocalRun\W\afq5-s, target branch: master, target branch commit: d4f35698aafe609fdf3bba8a90885cd0aca8fe2c, source commit: b7ecb4498e89815e23f6adfc1c2955a2e60761f5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5Cdba40f77-c0ca-7f55-919e-4973f36f2746%5CPullRequest%5C201911280652154205-5%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rBnMGXJyOfwKWVPeO22ryQKNkh5H%2BxZqDf6xyoOGVX0%3D&st=2019-11-28T06%3A47%3A27Z&se=2019-12-29T06%3A52%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[b7ecb44](https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz/commits/b7ecb4498e89815e23f6adfc1c2955a2e60761f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-41fa5bf3)

<a id="41fa5bf3"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz, working directory: C:\LocalRun\W\mmr0-s, target branch: master, target branch commit: d4f35698aafe609fdf3bba8a90885cd0aca8fe2c, source commit: b7ecb4498e89815e23f6adfc1c2955a2e60761f5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5Cdba40f77-c0ca-7f55-919e-4973f36f2746%5CPullRequest%5C201911280658562953-5%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WwdCk6lT6OAybo3fSBCRhqo7HSs8mxztu7mm1COTqDg%3D&st=2019-11-28T06%3A54%3A08Z&se=2019-12-29T06%3A59%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
