### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by ByronWU-Docs**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[b7ecb44](https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz/commits/b7ecb4498e89815e23f6adfc1c2955a2e60761f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e1a54b32)

<a id="e1a54b32"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz, working directory: C:\LocalRun\W\kxgy-s, target branch: master, target branch commit: d4f35698aafe609fdf3bba8a90885cd0aca8fe2c, source commit: b7ecb4498e89815e23f6adfc1c2955a2e60761f5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5Cdba40f77-c0ca-7f55-919e-4973f36f2746%5CPullRequest%5C201911280559449203-4%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HEozyHbEqVazwzoQkq5kUWCCEgHiUXb%2FJYd%2Bywmdr2w%3D&st=2019-11-28T05%3A54%3A58Z&se=2019-12-29T05%3A59%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[b7ecb44](https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz/commits/b7ecb4498e89815e23f6adfc1c2955a2e60761f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ea496673)

<a id="ea496673"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz, working directory: C:\LocalRun\W\p0ri-s, target branch: master, target branch commit: d4f35698aafe609fdf3bba8a90885cd0aca8fe2c, source commit: b7ecb4498e89815e23f6adfc1c2955a2e60761f5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5Cdba40f77-c0ca-7f55-919e-4973f36f2746%5CPullRequest%5C201911280612300642-4%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RevDz%2F4idXZhU3URBnyZO%2BY6VnXHmGmK1r0%2FgziOjSk%3D&st=2019-11-28T06%3A07%3A41Z&se=2019-12-29T06%3A12%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[b7ecb44](https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz/commits/b7ecb4498e89815e23f6adfc1c2955a2e60761f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4763b7ba)

<a id="4763b7ba"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz, working directory: C:\LocalRun\W\5rvz-s, target branch: master, target branch commit: d4f35698aafe609fdf3bba8a90885cd0aca8fe2c, source commit: b7ecb4498e89815e23f6adfc1c2955a2e60761f5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5Cdba40f77-c0ca-7f55-919e-4973f36f2746%5CPullRequest%5C201911280622175629-4%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nFC0so0pRQovUcW0KTz85nUaGLkreOj2UYhGkm44NyU%3D&st=2019-11-28T06%3A17%3A28Z&se=2019-12-29T06%3A22%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[b7ecb44](https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz/commits/b7ecb4498e89815e23f6adfc1c2955a2e60761f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5de03dc9)

<a id="5de03dc9"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/E2E_DocFxV3.cs-cz, working directory: C:\LocalRun\W\uyas-s, target branch: master, target branch commit: d4f35698aafe609fdf3bba8a90885cd0aca8fe2c, source commit: b7ecb4498e89815e23f6adfc1c2955a2e60761f5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5Cdba40f77-c0ca-7f55-919e-4973f36f2746%5CPullRequest%5C201911280627062481-4%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P5wb4B1ZhQ9K29TlQWNmeW1MJsr%2FmPQHN8WmiBZl7QM%3D&st=2019-11-28T06%3A22%3A17Z&se=2019-12-29T06%3A27%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
